CREATE TABLE Scores (
	ID INTEGER AUTO_INCREMENT,
	Player1ID INTEGER NOT NULL,
	Player2ID INTEGER NOT NULL,
	WinnerID INTEGER DEFAULT NULL,
	PRIMARY KEY (ID),
	FOREIGN KEY (Player1ID) REFERENCES Players(ID),
	FOREIGN KEY (Player2ID) REFERENCES Players(ID),
	FOREIGN KEY (WinnerID) REFERENCES Players(ID)
);